#!/bin/bash
# Online Registration Form - Setup & Deployment Script
# This script helps verify your setup and deployment

echo "======================================"
echo "Registration Form Setup Verification"
echo "======================================"
echo ""

# Check if files exist
echo "✓ Checking project files..."
FILES=("index.html" "style.css" "script.js" "process.php" "README.md" "QUICK_START.md")

for file in "${FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "  ✅ $file found"
    else
        echo "  ❌ $file MISSING"
    fi
done

echo ""
echo "======================================"
echo "LOCAL DEVELOPMENT SETUP"
echo "======================================"
echo ""
echo "1. Open VS Code"
echo "2. Go to Extensions (Ctrl+Shift+X)"
echo "3. Search for 'PHP Server' by brapifra"
echo "4. Click Install"
echo ""
echo "5. Right-click on index.html"
echo "6. Select 'PHP Server: Serve project'"
echo "7. Browser opens at localhost:3000"
echo ""

echo "======================================"
echo "TESTING CHECKLIST"
echo "======================================"
echo ""
echo "□ Form displays correctly"
echo "□ All input fields are visible"
echo "□ FontAwesome icons appear"
echo "□ Form is responsive on mobile"
echo "□ Submit button works"
echo "□ Validation shows errors"
echo "□ Success message displays"
echo "□ Data is logged to logs/ folder"
echo ""

echo "======================================"
echo "DEPLOYMENT OPTIONS"
echo "======================================"
echo ""
echo "INFINITYFREE (FREE & EASIEST):"
echo "  1. Sign up at infinityfree.net"
echo "  2. Upload files to htdocs folder"
echo "  3. Create logs folder with write permissions"
echo "  4. Access form at yourdomain.infinityfree.net"
echo ""
echo "HEROKU (PAID):"
echo "  1. Install Heroku CLI"
echo "  2. heroku login"
echo "  3. git init && git add . && git commit -m 'Initial'"
echo "  4. heroku create app-name"
echo "  5. git push heroku main"
echo ""

echo "======================================"
echo "FILE STRUCTURE"
echo "======================================"
echo ""
echo "project-root/"
echo "├── index.html        (Form HTML)"
echo "├── style.css         (Responsive CSS)"
echo "├── script.js         (jQuery & Validation)"
echo "├── process.php       (Backend PHP)"
echo "├── composer.json     (Heroku config)"
echo "├── Procfile          (Heroku process)"
echo "├── .htaccess         (Apache config)"
echo "├── database.sql      (Database schema)"
echo "├── logs/             (Data logging)"
echo "├── README.md         (Full docs)"
echo "└── QUICK_START.md    (Quick reference)"
echo ""

echo "======================================"
echo "QUICK TEST"
echo "======================================"
echo ""
echo "Test with this data:"
echo "  Full Name: John Doe"
echo "  Email: john@example.com"
echo "  Phone: +1234567890"
echo "  Password: Test@123"
echo "  Confirm: Test@123"
echo ""
echo "Expected: Success message, data in logs/"
echo ""

echo "======================================"
echo "✓ Setup Complete!"
echo "======================================"
echo ""
echo "Next Steps:"
echo "1. Read QUICK_START.md for 3-step setup"
echo "2. Read README.md for full documentation"
echo "3. Test the form locally"
echo "4. Deploy when ready"
echo ""
